---
all:
  vars:
    ansible_connection: ssh
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    vault_aio:
      hosts:
        vault-aio:
          ansible_host: 10.0.0.20
          ansible_user: aeonuser
          ansible_ssh_private_key_file: "{{ playbook_dir }}/vault-aio-key"
      vars:
        vm_role: vault-aio
        vm_type: vault_standalone
